name: backend-pipeline

on:
  push:
    branches:
      - main
    # paths:
    #   - 'backend/**'
    paths-ignore:
      - 'k8s/backend/backend-deployment.yaml'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    environment: backend_git_actions
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application.yml directory
        run: mkdir -p ./backend/src/main/resources

      - name: Copy config file
        env:
          APPLICATION_YML_BASE64: ${{ secrets.APPLICATION_YML_BASE64 }}
        run: |
          echo "$APPLICATION_YML_BASE64" | base64 -d > ./backend/src/main/resources/application.yml

      - name: Build Backend
        run: |
          cd ./backend
          chmod +x gradlew
          ./gradlew build
          ls ./build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: ./backend/build/libs/*.jar

  docker-build-push:
    runs-on: ubuntu-latest
    environment: backend_git_actions
    needs: build-backend
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: backend-jar
          path: ./backend/build/libs


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ls
        run: |
          ls ./backend/build

      - name: Build and push Docker image
        run: |
          cd ./backend
          DOCKER_IMAGE_TAG="1.${{ github.run_number }}-be"
          docker build --no-cache -t ${{ secrets.DOCKER_HUB_REPO }}:$DOCKER_IMAGE_TAG .
          docker push ${{ secrets.DOCKER_HUB_REPO }}:$DOCKER_IMAGE_TAG

  # deploy-backend:
  #   runs-on: ubuntu-latest
  #   environment: backend_git_actions
  #   needs: docker-build-push
  #   steps:
  #     - name: Set up kubectl
  #       run: |
  #         echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config

  #     - name: Deploy to Kubernetes
  #       env:
  #         DOCKER_IMAGE_TAG: "1.${{ github.run_number }}-be"
  #       run: |
  #         kubectl set image deployment backend-deployment backend-container=${{ secrets.DOCKER_HUB_REPO }}:$DOCKER_IMAGE_TAG -n default

  update-deployment-file:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Update deployment.yaml
        env:
          DOCKER_IMAGE_TAG: "1.${{ github.run_number }}-be"
        run: |
          sed -i "s|henhen7/be08-4th-2team:.*|${{ secrets.DOCKER_HUB_REPO }}:${{ env.DOCKER_IMAGE_TAG }}|g" k8s/backend/backend-deployment.yaml
          cat k8s/backend/backend-deployment.yaml  # 변경 내용 확인

      - name: Commit & Push changes
        env:
          GIT_USER: "eatho"
          GIT_EMAIL: "eatho@naver.com"
        run: |
          git config user.name "$GIT_USER"
          git config user.email "$GIT_EMAIL"
          git add k8s/backend/backend-deployment.yaml
          git commit -m "Update Image Version to $DOCKER_IMAGE_TAG"
          git push

  notify-discord:
    runs-on: ubuntu-latest
    needs: [build-backend, docker-build-push, update-deployment-file]
    if: always()
    steps:
      - name: Send notification to Discord
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -d '{"content":"**CI/CD Pipeline Success**\n'\
                  'Build Number: '${{ github.run_number }}\'}' \
